/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  yyinteg.c
 *  subm:  PositionControllerTilt
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 13, 2026
 *  time:  12:29:13 PM
 *  user:  Universiteit Twente
 *  from:  -
 *  build: 5.1.6.14106
 **********************************************************/

/* This file describes the integration methods
   that are supplied for computation.

   Currently the following methods are supported:
   * Discrete
   * Euler
   * RungeKutta2
   * RungeKutta4
   but it is easy for the user to add their own
   integration methods with these as examples.
*/

/* the system include files */
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* our own include files */
#include "yyinteg.h"
#include "yymodel.h"

/* global variables prototypes */
extern YYDouble yy_time;
extern YYDouble yy_step_size;

#define yy_STATE_SIZE 3

/*********************************************************************
 * Discrete integration method
 *********************************************************************/

/* the initialization of the Discrete integration method */
void YYDiscreteInitialize (void)
{
	/* nothing to be done */
	yy_major = YYTRUE;
}

/* the termination of the Discrete integration method */
void YYDiscreteTerminate (void)
{
	/* nothing to be done */
}

/* the Discrete integration method itself */
void YYDiscreteStep (void)
{
	YYInteger index;

	/* for each of the supplied states */
	for (index = 0; index < yy_STATE_SIZE; index++)
	{
		/* just a move of the new state */
		yy_s [index] = yy_R [index];
	}
	/* increment the simulation time */
	yy_time += yy_step_size;

	yy_major = YYTRUE;

	/* evaluate the dynamic part to calculate the new rates */
	YYCalculateDynamic ();
}

