/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  yymodel.h
 *  subm:  PositionControllerTilt
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 13, 2026
 *  time:  12:29:13 PM
 *  user:  Universiteit Twente
 *  from:  -
 *  build: 5.1.6.14106
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the yymodel.c file
*/

#ifndef YY_MODEL_H
#define YY_MODEL_H

/* Our own include files */
#include "yytypes.h"

/* Simulation variables */
extern YYDouble yy_start_time;
extern YYDouble yy_finish_time;
extern YYDouble yy_step_size;
extern YYDouble yy_time;
extern YYInteger yy_steps;
extern YYBoolean yy_initialize;
extern YYBoolean yy_major;
extern YYBoolean yy_stop_simulation;

/* Model size constants */
#define yy_constants_size 0
#define yy_parameters_size 7
#define yy_initialvalues_size 3
#define yy_variables_size 12
#define yy_states_size 3

/* Variable arrays */
extern YYDouble yy_P[];
extern YYDouble yy_I[];
extern YYDouble yy_V[];
extern YYDouble yy_s[];
extern YYDouble yy_R[];


/* The names of the variables as used in the arrays above
   uncomment this if you need the names (see source file too)
extern YYString yy_parameter_names[];
extern YYString yy_initial_value_names[];
extern YYString yy_variable_names[];
extern YYString yy_state_names[];
extern YYString yy_rate_names[];
*/

/* Initialization methods */
/* Initialize complete model */
void YYModelInitialize (void);
/* Initialize specific model values */
void YYModelInitialize_parameters(void);
void YYModelInitialize_initialvalues(void);
void YYModelInitialize_states(void);
void YYModelInitialize_variables(void);
void YYModelTerminate (void);

/* Computation methods */
void YYCalculateInitial (void);
void YYCalculateStatic (void);
void YYCalculateInput (void);
void YYCalculateDynamic (void);
void YYCalculateOutput (void);
void YYCalculateFinal (void);


#endif

