/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  yysubmod.c
 *  subm:  PositionControllerTilt
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 13, 2026
 *  time:  12:29:13 PM
 *  user:  Universiteit Twente
 *  from:  -
 *  build: 5.1.6.14106
 **********************************************************/

/* Standard include files */
#include <stdlib.h>

/* 20-sim include files */
#include "yymodel.h"
#include "yyinteg.h"
#include "yyfuncs.h"
#include "yysubmod.h"
#include "motionprofiles.h"
#include "EulerAngles.h"

/* The submodel I/O variables */
YYInteger yy_number_of_inputs = 3;
YYInteger yy_number_of_outputs = 1;

/* the names of the submodel io variables
   uncomment this part if you need these names
YYString yy_input_names[] = {
	"corr",
	"in",
	"position"
,	NULL
};
YYString yy_output_names[] = {
	"out"
,	NULL
};
*/
/* This function sets the input variables from the input vector */
void YYCopyInputsToVariables (YYDouble *u)
{
	/* Copy the input vector to the input variables */
	yy_V[8] = u[0];		/* corr */
	yy_V[9] = u[1];		/* in */
	yy_V[10] = u[2];		/* position */

}

/* This function uses the output variables to fill the output vector */
void YYCopyVariablesToOutputs (YYDouble *y)
{
	/* Copy the output variables to the output vector */
	y[0] = 	yy_V[11];		/* out */

}

/* The initialization function for submodel */
void YYInitializeSubmodel (YYDouble *u, YYDouble *y, YYDouble t)
{
	/* Initialization phase (allocating memory) */
	yy_initialize = YYTRUE;
	yy_steps = 0;
	YYModelInitialize ();
	YYDiscreteInitialize ();

	/* Copy the inputs */
	yy_time = t;
	YYCopyInputsToVariables (u);

	/* Calculate the model for the first time */
	YYCalculateInitial ();
	YYCalculateStatic ();
	YYCalculateInput ();
	YYCalculateDynamic ();
	YYCalculateOutput ();

	/* Set the outputs */
	YYCopyVariablesToOutputs (y);

	/* End of initialization phase */
	yy_initialize = YYFALSE;
}

/* The function that calculates the submodel */
void YYCalculateSubmodel (YYDouble *u, YYDouble *y, YYDouble t)
{
	/* Copy the inputs */
	yy_time = t;
	YYCopyInputsToVariables (u);

	/* Calculate the model */
	YYCalculateInput ();
	YYDiscreteStep ();
	YYCalculateOutput ();

	/* Copy the outputs */
	YYCopyVariablesToOutputs (y);
}

/* The termination function for submodel */
void YYTerminateSubmodel (YYDouble *u, YYDouble *y, YYDouble t)
{
	/* Copy the inputs */
	yy_time = t;
	YYCopyInputsToVariables (u);

	/* Calculate the final model equations */
	YYCalculateFinal ();

	/* Set the outputs */
	YYCopyVariablesToOutputs (y);

	/* and terminate the model itself (releasing memory) */
	YYModelTerminate ();
	YYDiscreteTerminate ();
}

