/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  yyfuncs.h
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 13, 2026
 *  time:  12:29:13 PM
 *  user:  Universiteit Twente
 *  from:  -
 *  build: 5.1.6.14106
 **********************************************************/

#ifndef YY_FUNCS_H
#define YY_FUNCS_H

/* Our own include files */
#include "yytypes.h"

/* Global constants */
extern YYBoolean yy_initialize;
extern YYBoolean yy_major;
extern YYBoolean yy_stop_simulation;

/* Wrapper functions around strings */
YYDouble YYString2Double(const char* argument);
const char* YYDouble2String(YYDouble argument);

/* 20-sim function prototypes */
/* 20-sim stub prototypes */
#endif

