/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  yysubmod.h
 *  subm:  PositionControllerTilt
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 13, 2026
 *  time:  12:29:13 PM
 *  user:  Universiteit Twente
 *  from:  -
 *  build: 5.1.6.14106
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the yymodel.c file
*/

#ifndef YY_SUBMOD_H
#define YY_SUBMOD_H

/* Our own include files */
#include "yymodel.h"

/* Submodel I/O variables */
extern YYInteger yy_number_of_inputs;
extern YYInteger yy_number_of_outputs;

/* The names of the variables as used in the arrays above */
extern YYString yy_input_names[];
extern YYString yy_output_names[];


/* The submodel functions */
void YYInitializeSubmodel (YYDouble *u, YYDouble *y, YYDouble t);
void YYCalculateSubmodel (YYDouble *u, YYDouble *y, YYDouble t);
void YYTerminateSubmodel (YYDouble *u, YYDouble *y, YYDouble t);
void YYCopyInputsToVariables (YYDouble *u);
void YYCopyVariablesToOutputs (YYDouble *y);

#endif

