/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  yytypes.h
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 13, 2026
 *  time:  12:29:13 PM
 *  user:  Universiteit Twente
 *  from:  -
 *  build: 5.1.6.14106
 **********************************************************/

/* This file describes the typedefs that are used for integers and
   doubles. All the generated code uses these typedefs to enhance
   flexibility (in case the compiler is not Visual C++ 6 or the destination
   platform is not Windows 2000 on a Pentium 4).
   
   The user should be aware of the precision of these types, when
   these types are changed! For instance, when the destination platform 
   is a particular 8051 that does not support any doubles at all,
   one might change the YYDouble type into some float of 4 bytes.
   The results may then differ from the 20-sim results. It is advised
   to check these differences by running the code with both settings
   on the PC first (as far as this is possible).
   
   In 20-sim the following definitions are used:
   
    typedef YYDouble double;
    typedef YYInteger int;
   
   so that 
   
    YYDouble is 8 bytes (64 bits) with a range of [-1.7E+308, 1.7E+308]
    YYInteger is 4 bytes (32 bits) with a range of [-2147483648, 2147483647]
    YYCharacter is 1 byte (8 bits) with a value of [0, 255]
    YYBoolean is 1 byte (8 bits) with a value of 0 or 1
*/ 

#ifndef YY_TYPES_H
#define YY_TYPES_H

/* The mentioned typedefs */
typedef double YYDouble;
typedef int YYInteger;
typedef char YYCharacter;
typedef char YYBoolean;
typedef const char* YYString;

/* Defines */
#define YYTRUE  1
#define YYFALSE 0

#endif

