/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  motionprofiles.c
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 11, 2026
 *  time:  3:13:06 PM
 *  user:  Universiteit Twente
 *  from:  -
 *  build: 5.1.6.14106
 **********************************************************/

/* This file implements the functions necessary for motion profiles
   functions
*/

