/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  yyinverse.c
 *  subm:  PositionControllerTilt
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 13, 2026
 *  time:  12:29:13 PM
 *  user:  Universiteit Twente
 *  from:  -
 *  build: 5.1.6.14106
 **********************************************************/

/* No matrix support functions are needed for this model */

