/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  yymodel.c
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 13, 2026
 *  time:  12:29:13 PM
 *  user:  Universiteit Twente
 *  from:  -
 *  build: 5.1.6.14106
 **********************************************************/

/* This file contains the actual model variables and equations */

/* Note: Alias variables are the result of full optimization
   of the model in 20-sim. As a result, only the real variables
   are used in the model for speed. The user may also include
   the alias variables by adding them to the end of the array:

   YYDouble yy_variables[NUMBER_VARIABLES + NUMBER_ALIAS_VARIABLES + 1];
   YYString yy_variable_names[] = {
     VARIABLE_NAMES, ALIAS_VARIABLE_NAMES, NULL
   };

   and calculate them directly after the output equations:

   void YYCalculateOutput (void)
   {
     OUTPUT_EQUATIONS
     ALIAS_EQUATIONS
   }
*/

/* system include files */
#include <stdlib.h>
#include <math.h>
#include <string.h>

/* 20-sim include files */
#include "yymodel.h"
#include "yyfuncs.h"

/* the global variables */
YYDouble yy_start_time = 0.0;
YYDouble yy_finish_time = 20.0;
YYDouble yy_step_size = 0.01;
YYDouble yy_time = 0.0;
YYInteger yy_steps = 0;
YYBoolean yy_initialize = YYTRUE;
YYBoolean yy_major = YYTRUE;
YYBoolean yy_stop_simulation = YYFALSE;

/* the variable arrays */
YYDouble yy_P[yy_parameters_size];		/* parameters */
YYDouble yy_I[yy_initialvalues_size];		/* initial values */
YYDouble yy_V[yy_variables_size];		/* variables */
YYDouble yy_s[yy_states_size];		/* states */
YYDouble yy_R[yy_states_size];		/* rates (or new states) */

/* the names of the variables as used in the arrays above
   uncomment this part if these names are needed
YYString yy_parameter_names[] = {
	"corrGain\\K",
	"PID1\\kp",
	"PID1\\tauD",
	"PID1\\beta",
	"PID1\\tauI",
	"SignalLimiter2\\minimum",
	"SignalLimiter2\\maximum"
,	NULL
};
YYString yy_initial_value_names[] = {
	"PID1\\uD_previous_initial",
	"PID1\\error_previous_initial",
	"PID1\\uI_previous_initial"
,	NULL
};
YYString yy_variable_names[] = {
	"corrGain\\input",
	"corrGain\\output",
	"PID1\\output",
	"",
	"PlusMinus1\\output",
	"PlusMinus2\\plus1",
	"PlusMinus2\\minus1",
	"SignalLimiter2\\output",
	"corr",
	"in",
	"position",
	"out"
,	NULL
};
YYString yy_state_names[] = {
	"PID1\\uD_previous",
	"PID1\\error_previous",
	"PID1\\uI_previous"
,	NULL
};
YYString yy_rate_names[] = {
	"",
	"PID1\\error",
	""
,	NULL
};
*/

#if (7 > 8192) && defined _MSC_VER
#pragma optimize("", off)
#endif
void YYModelInitialize_parameters(void)
{
	/* set the parameters */
	yy_P[0] = 0.0;		/* corrGain\K */
	yy_P[1] = 1.6;		/* PID1\kp */
	yy_P[2] = 0.3;//0.05;		/* PID1\tauD */
	yy_P[3] = 0.001;		/* PID1\beta */
	yy_P[4] = 10.5;		/* PID1\tauI */
	yy_P[5] = -0.99;		/* SignalLimiter2\minimum */
	yy_P[6] = 0.99;		/* SignalLimiter2\maximum */

}
#if (7 > 8192) && defined _MSC_VER
#pragma optimize("", on)
#endif

void YYModelInitialize_initialvalues(void)
{
	/* set the initial values */
	yy_I[0] = 0.0;		/* PID1\uD_previous_initial */
	yy_I[1] = 0.0;		/* PID1\error_previous_initial */
	yy_I[2] = 0.0;		/* PID1\uI_previous_initial */

}

void YYModelInitialize_states(void)
{
	/* set the states */
	yy_s[0] = yy_I[0];		/* PID1\uD_previous */
	yy_s[1] = yy_I[1];		/* PID1\error_previous */
	yy_s[2] = yy_I[2];		/* PID1\uI_previous */

}

void YYModelInitialize_variables(void)
{
	/* initialize the variable memory to zero */
	memset(yy_V, 0, yy_variables_size * sizeof(YYDouble));
}

/* this method is called before calculation is possible */
void YYModelInitialize (void)
{
	YYModelInitialize_parameters();
	YYModelInitialize_variables();
	YYModelInitialize_initialvalues();
	YYModelInitialize_states();
}

/* This function calculates the initial equations of the model.
 * These equations are calculated before anything else
 */
void YYCalculateInitial (void)
{

	/* set the states again, they might have changed in the initial calculation */
	YYModelInitialize_states ();
}

/* This function calculates the static equations of the model.
 * These equations are only dependent from parameters and constants
 */
void YYCalculateStatic (void)
{

}

/* This function calculates the input equations of the model.
 * These equations are dynamic equations that must not change
 * in calls from the integration method (like random and delay).
 */
void YYCalculateInput (void)
{

}

/* This function calculates the dynamic equations of the model.
 * These equations are called from the integration method
 * to calculate the new model rates (that are then integrated).
 */
void YYCalculateDynamic (void)
{
	/* PID1\factor = 1 / (sampletime + PID1\tauD * PID1\beta); */
	yy_V[3] = 1.0 / (yy_step_size + yy_P[2] * yy_P[3]);

	/* corrGain\input = corr; */
	yy_V[0] = yy_V[8];

	/* PlusMinus2\plus1 = in; */
	yy_V[5] = yy_V[9];

	/* PlusMinus2\minus1 = position; */
	yy_V[6] = yy_V[10];

	/* corrGain\output = corrGain\K * corrGain\input; */
	yy_V[1] = yy_P[0] * yy_V[0];

	/* PID1\error = PlusMinus2\plus1 - PlusMinus2\minus1; */
	yy_R[1] = yy_V[5] - yy_V[6];

	/* PID1\uD = PID1\factor * (((PID1\tauD * PID1\uD_previous) * PID1\beta + (PID1\tauD * PID1\kp) * (PID1\error - PID1\error_previous)) + (sampletime * PID1\kp) * PID1\error); */
	yy_R[0] = yy_V[3] * (((yy_P[2] * yy_s[0]) * yy_P[3] + (yy_P[2] * yy_P[1]) * (yy_R[1] - yy_s[1])) + (yy_step_size * yy_P[1]) * yy_R[1]);

	/* PID1\uI = PID1\uI_previous + (sampletime * PID1\uD) / PID1\tauI; */
	yy_R[2] = yy_s[2] + (yy_step_size * yy_R[0]) / yy_P[4];

	/* PID1\output = PID1\uI + PID1\uD; */
	yy_V[2] = yy_R[0];//yy_R[2] + yy_R[0];

	/* PlusMinus1\output = corrGain\output + PID1\output; */
	yy_V[4] = yy_V[1] + yy_V[2];

	/* SignalLimiter2\output = if PlusMinus1\output < SignalLimiter2\minimum... ; */
	yy_V[7] = ((yy_V[4] < yy_P[5]) ? 
		/* SignalLimiter2\minimum */
		yy_P[5]
	:
		/* if PlusMinus1\output > SignalLimiter2\maximum...  */
		((yy_V[4] > yy_P[6]) ? 
			/* SignalLimiter2\maximum */
			yy_P[6]
		:
			/* PlusMinus1\output */
			yy_V[4]
		)
	);


	/* increment the step counter */
	yy_steps++;
}

/* This function calculates the output equations of the model.
 * These equations are not needed for calculation of the rates
 * and are kept separate to make the dynamic set of equations smaller.
 * These dynamic equations are called often more than one time for each
 * integration step that is taken. This makes model computation much faster.
 */
void YYCalculateOutput (void)
{
	/* out = SignalLimiter2\output; */
	yy_V[11] = yy_V[7];

}

/* This function calculates the final equations of the model.
 * These equations are calculated after all the calculations
 * are performed
 */
void YYCalculateFinal (void)
{

}

/* this method is called after all calculations are performed */
void YYModelTerminate(void)
{
}

