/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  yyinteg.h
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 13, 2026
 *  time:  12:29:13 PM
 *  user:  Universiteit Twente
 *  from:  -
 *  build: 5.1.6.14106
 **********************************************************/

/* This file describes the integration methods
that are supplied for computation.

   Currently the following methods are supported:
   * Euler
   * RungeKutta2
   * RungeKutta4
   but it is easy for the user to add their own
   integration methods with these two as an example.
*/

#ifndef YY_INTEG_H
#define YY_INTEG_H

/* 20-sim include files */
#include "yytypes.h"

/* the chosen integration method */
#define Discrete_METHOD

/* the integration methods */
void YYDiscreteInitialize (void);
void YYDiscreteTerminate (void);
void YYDiscreteStep (void);

extern YYBoolean yy_major;

#endif

