/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  yymain.c
 *  subm:  PositionControllerTilt
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 13, 2026
 *  time:  12:29:13 PM
 *  user:  Universiteit Twente
 *  from:  -
 *  build: 5.1.6.14106
 **********************************************************/

/* This file is a demo application of how the submodel function can 
 * be used. It uses the global time variables that are used by both
 * the submodel and the integration method.
 *
 * PLEASE NOTE: THIS IS AN EXAMPLE WHERE ALL INPUTS ARE ZERO ! 
 * USE YOUR OWN INPUTS INSTEAD!! ALSO THE SUBMODEL MIGHT SIMPLY 
 * NOT WORK CORRECTLY WITH INPUTS THAT ARE ZERO.
 */

/* 20-sim include files */
#include "yysubmod.h"

/* The main function */
int main()
{
	YYDouble u [3 + 1];
	YYDouble y [1 + 1];

	/* Initialize the inputs and outputs with correct initial values */
	u[0] = 0.0;		/* corr */
	u[1] = 0.0;		/* in */
	u[2] = 0.0;		/* position */

	y[0] = 0.0;		/* out */


	/* Initialize the submodel itself */
	YYInitializeSubmodel (u, y, yy_time);

	/* Simple loop, the time is incremented by the integration method */
	while ( (yy_time < yy_finish_time) && (yy_stop_simulation == YYFALSE) )
	{
		/* Call the submodel to calculate the output */
		YYCalculateSubmodel (u, y, yy_time);
	}

	/* Perform the final calculations */
	YYTerminateSubmodel (u, y, yy_time);

	/* and we are done */
	return 0;
}

