/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxmatrix.h
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 11, 2026
 *  time:  3:13:06 PM
 *  user:  Universiteit Twente
 *  from:  -
 *  build: 5.1.6.14106
 **********************************************************/
/* Empty file, no matrix support functions are needed for this model */


